name: Juice Shop CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
        
      - name: Build project
        run: npm install
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  dast:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/zaproxy/zaproxy:stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Стартуем Juice Shop как внешний процесс
      - name: Start Juice Shop
        run: |
          apt-get update && apt-get install -y curl gnupg
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs
          npm ci
          npm start &  # стартуем сервер
          sleep 15     # даём время на запуск

      # Запускаем ZAP Full Scan
      - name: Run OWASP ZAP Scan
        run: |
          zap-full-scan.py \
            -t http://host.docker.internal:3000 \
            -r zap-report.html \
            -J zap-report.json \
            -d -I || true  # Не падаем, даже если найдены уязвимости

      # Сохраняем отчёт
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html
